### ISSUE TITLE
fix bug concerning installation

### ISSUE THREAD

**Issue by grewered** [weirichs/eatModel#8]
the master branch fails at the moment. Error message says it's something to do with installation as you can see here: https://github.com/weirichs/eatModel/actions/runs/10946694839/job/30393783413

**Comment by grewered** [comment]
@weirichs should I ignore that for now?

**Comment by weirichs** [comment]
> @weirichs should I ignore that for now?

This error was already stated by @nickhaf and results from inappropriate ASCII character coding set in `getResults.rd` (it should be UTF-8, not ISO-8859-1). However, the problem was already solved and a corrected file was pushed (I think, in the master branch), so I do not understand why this error still occurred. Maybe it's a merge conflict. 
I've changed coding scheme from ISO-8859-1 to UTF-8 again in the master branch. However, branches should be merged until the changes apply. So I would suggest to merge the branches first and than continue with restructuring?

**Comment by weirichs** [comment]
The last error occurring in eatModel stated by @grewered and @nickhaf 
`https://github.com/weirichs/eatModel/actions/runs/11084757409/job/30800407338#step:6:403`
has other causes. It's a problem in `eatTools::recodeLookup()`:
```r
Error in names(add_lookup) <- names(lookup) : 
  'names' attribute [2] must be the same length as the vector [0]
```
I've fixed the error in eatTools. As the fix isn't implemented in the CRAN version yet, I added a few lines in the eatModel DESCRIPTION file to make eatModel use the package version from github instead of CRAN. Hope that works:
```
Remotes:
    weirichs/eatTools
```

**Comment by nickhaf** [comment]
I still have problems installing the package (this time on Windows):

```
Error: Laden von Paket oder Namensraum für 'eatModel' in namespaceExport(ns, exports): fehlgeschlagen
 nicht definierte Exporte: prepRep
Fehler: Laden fehlgeschlagen
Ausführung angehalten
ERROR: loading failed
* removing 'C:/Users/hafiznij/Documents/GitHub/test_actions_2/renv/library/windows/R-4.4/x86_64-w64-mingw32/eatModel'
Warnmeldungen:
1: In untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
3: In untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
4: In untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
5: In i.p(...) :
  Installation des Pakets ‘C:/Users/hafiznij/AppData/Local/Temp/RtmpmIa7s5/file50f0409c6373/eatModel_0.8.36.tar.gz’ hatte Exit-Status ungleich 0
```

**Comment by beckerbenj** [comment]
In the namespace, `prepRep()` is still being exported, while the function itself was removed from the package by @grewered in 419ecfe39f33bcba905889c57a535c20cc7a372c.

**Comment by weirichs** [comment]
Ok, I've removed `prepRep()` from namespace export. Hope it should work now ...
